### ISSUE TITLE
Docker Container? 

### ISSUE THREAD

**Issue by gkenyon** [BitCurator/bitcurator-distro#1]
Just getting started digging into the app and documentation, this project seems great, and I was wondering if a Docker container is on the development roadmap at all? Thanks!

**Comment by kamwoods** [comment]
Not currently, but the projects are always open to community contributions.

**Comment by digitalsleuth** [comment]
@kamwoods , since the successful creation of the CLI and the new bitcurator-salt repo, I have updated my BitCurator docker. 
I've posted the Dockerfile contents and the docker-compose.yaml file if you want to create a separate repo for it and create a BitCurator build for it. Feel free to try it out and check out the details [here](https://hub.docker.com/r/digitalsleuth/bitcurator).

**Comment by kamwoods** [comment]
@digitalsleuth , thanks! I've added the files to a new repo at https://github.com/bitcurator/bitcurator-docker. Created and tagged an image and pushed it to https://hub.docker.com/r/bitcurator/bitcurator where I just replicated the relevant part of your text for the README. Acknowledgements on both - let me know if anything looks amiss.

@gkenyon , it's been quite a long time but if you're still interested, here we are. Note that there will be some modest changes coming soon to the environment configuration and included tools. Also, there hasn't yet been an announcement to the BitCurator Consortium regarding the new Focal-based builds or the docker container, and documentation on various sites needs to be further updated to reflect their availability. Coming soon.

**Comment by kamwoods** [comment]
The BitCurator docker files originally contributed by @digitalsleuth have been updated to use the latest release of our CLI (1.0.0), the Saltstack 3005 release, and now default to building in a Jammy (22.04) base with - at the time of writing - the BitCurator 4.2.1 release. They could probably use some additional documentation and will likely get ongoing updates, but as of now they function as desired. The links from my previous reply remain the same. Closing this issue now; if you run into technical issues with the docker repo or hub images, please open a new issue at https://github.com/bitcurator/bitcurator-docker!
