### ISSUE TITLE
Bitcurator offers no option to uninstall or revert

### ISSUE THREAD

**Issue by kage1414** [BitCurator/bitcurator-distro#3]
Not sure if this is the correct repo for this issue...please move if needed.

Recently installed bitcurator in an Ubuntu VM to try it out (I'm a dev, my partner works in a museum and I was trying to get it set up for her to see if it would fit her needs). Unfortunately, it seems to have overridden my previous Ubuntu configuration. This will be tricky to try an revert.

It would be nice if Bitcurator offered the option to revert the config after install. Additionally, adding a flag to disallow overriding the current Ubuntu config.

**Comment by kamwoods** [comment]
BitCurator has several different installation modes documented in our Quickstart Guide (linked at https://github.com/BitCurator/bitcurator-distro/wiki/Releases). One of these is "addon" (see page 12). If you install in addon mode, the default Ubuntu theme and boot splash will be left intact. I can update the Quickstart in a future rendition to foreground this a bit more. But yes, a complete uninstall is not currently an option.

If you want to try BitCurator out without changing anything in your existing environment, we also distribute a Virtual Appliance that can be run in VirtualBox (linked on the same page).

**Comment by digitalsleuth** [comment]
Closing as no further response was received or required.
