### ISSUE TITLE
Installing VirtualBox guest additions before BitCurator requires additional dependencies

### ISSUE THREAD

**Issue by jfcarrano** [BitCurator/bitcurator-distro#5]
When attempting to install VirtualBox guest additions in the Ubuntu VM before installing BitCurator as suggested by the [quick start guide](https://github.com/BitCurator/bitcurator-distro/wiki/BitCurator-Quick-Start-Guide#important-notes-for-virtualbox-vm-installations), I receive an error: `This system is currently not set up to build kernel modules.
Please install the gcc make perl packages from your distribution.` 

The [top answer here](https://askubuntu.com/questions/1035030/this-system-is-currently-not-set-up-to-build-kernel-modules-when-trying-to-ins) works to fix that. I see that the BitCurator installer does install these packages later as well. Should the quick start guide be adjusted to mention the need for an additional step before installing guest additions? Or can guest additions be installed later once the BitCurator installer has installed the needed packages?

**Comment by kamwoods** [comment]
The relevant section in the Quickstart has been modified.

**Comment by jfcarrano** [comment]
thanks!
